Adds dnodeOpts to disable `weak` option of dnode
fixes Error: Cannot find module 'weak'
see https://github.com/sgentle/phantomjs-node#use-it-in-windows

example:
var prerender = require('prerender');
var server = prerender({
    dnodeOpts: { weak: false }
});
server.start();